apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "identity.fullname" . }}
  labels:
    {{- include "identity.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "identity.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "identity.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "identity.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion}}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: {{ .Values.backend.service.name }}
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}    
          envFrom:
          - configMapRef:
              name: {{ .Values.globalConfigMapName }}
          - configMapRef:
              name: {{ .Values.IdentityConfigMapName }}
          - secretRef:
              name: {{ .Values.IdentitySecretName }}
          - secretRef:
              name: {{ .Values.globalSecretName }}
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: APP_VERSION
            value: "{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          {{- range $key, $value := .Values.backend.env }}
          {{- if and (ne $key "POD_NAME") (ne $key "APP_VERSION") }}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          {{- range $key, $value := .Values.env }}
          {{- if and (ne $key "POD_NAME") (ne $key "APP_VERSION") }}
          - name: {{ $key | quote }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}

