replicaCount: 1

image:
  repository: images.paas.redhat.com/unifai/slack-proxy-nginx
  pullPolicy: Always
  tag: "latest"

appServiceName: "unifai-backend"
appServicePort: 8005
apiEndpoint: "/api/slack_commands/commands"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: LoadBalancer
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 250m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
