apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.volumeName }}
  labels:
    {{- include "logging.labels" . | nindent 4 }}
    {{- with .Values.storage.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- $extraAnnotations := .Values.storage.annotations | default dict }}
  {{- if or .Values.storage.keepPvc (not (empty $extraAnnotations)) }}
  annotations:
  {{- if .Values.storage.keepPvc }}
    "helm.sh/resource-policy": keep
  {{- end }}
  {{- if not (empty $extraAnnotations) }}
    {{- toYaml $extraAnnotations | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  {{- with .Values.storage }}
  accessModes:
    {{- toYaml .accessModes | nindent 4 }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .requestedSize }}
  {{- if .className }}
  storageClassName: {{ .className }}
  {{- end }}
  {{- end }}
