apiVersion: v1
kind: Service
metadata:
  name: {{ include "logging.fullname" . }}
  labels:
    {{- include "logging.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port_grpc }}
      targetPort: {{ .Values.service.port_grpc }}
      protocol: TCP
      name: port_grpc
    - port: {{ .Values.service.port_http }}
      targetPort: {{ .Values.service.port_http }}
      protocol: TCP
      name: port_http
    - port: {{ .Values.service.port_ui }}
      targetPort: {{ .Values.service.port_ui }}
      protocol: TCP
      name: port_ui
  selector:
    app: {{ include "logging.name" . }}
