unifai_backend:
  debug: false
  replicaCount: 1
  image:
    repository: images.paas.redhat.com/unifai/backend
    tag: "latest"
    pullPolicy: Always
  env:
    BACKEND_ENV: "production"
    RAG_URL: "http://unifai-rag-server:13457"
    MULTIAGENT_URL: "http://unifai-multiagent-be:8003"
    VERSION: ""
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
