env:
    qdrant_ip: "http://qdrant"
    qdrant_port: "6333"
    SHARED_STORAGE: "/app/shared"

unifai_dataflow_server:
  debug: false
  replicaCount: 1
  image:
    repository: images.paas.redhat.com/unifai/rag
    tag: "latest"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 13456
  env:
    ROLE: "flask"
    SHARED_STORAGE: "/app/shared"
    VERSION: ""
    #FRONTEND_URL: "http://unifai-ui-tag-ai--pipeline.apps.stc-ai-e1-pp.imap.p1.openshiftapps.com"
  resources:
    limits:
      cpu: 4
      memory: 12Gi
    requests:
      cpu: 4
      memory: 12Gi


unifai_dataflow_celery:
  debug: false
  replicaCount: 1
  image:
    repository: images.paas.redhat.com/unifai/rag
    tag: "latest"
    pullPolicy: Always
  env:
    ROLE: "celery"
    SHARED_STORAGE: "/app/shared"
    CELERY_QUEUES: "slack_queue,document_queue,slack_events_queue"
    CELERY_WORKER: 1
    VERSION: ""
  resources:
    limits:
      cpu: 4
      memory: 8Gi
      nvidia.com/gpu: 1
    requests:
      cpu: 2
      memory: 4Gi
      nvidia.com/gpu: 1
  tolerations: []