env:
  FRONTEND_URL: "https://unifai-ui-tag-ai--pipeline.apps.stc-ai-e1-pp.imap.p1.openshiftapps.com"
  DATAPIPELINEHUB_HOST:  "unifai-dataflow-server"
  DATAPIPELINEHUB_PORT: "13456"
  MULTIAGENT_HOST: "unifai-multiagent-be"
  MULTIAGENT_PORT: "8003"
  SSO_BACKEND_HOST: "https://unifai-sso-backend-tag-ai--pipeline.apps.stc-ai-e1-pp.imap.p1.openshiftapps.com"
  
  # TODO : follow up story for sso-nginx GENIE-812
  #SSO_NGINX_HOST: "https://unifai-sso-nginx-tag-ai--pipeline.apps.stc-ai-e1-prod.rtc9.p1.openshiftapps.com"