multiagent_server:
  replicaCount: 1
  resources:
    limits:
      cpu: '1'
      memory: '2Gi'
    requests:
      cpu: '1'
      memory: '2Gi'
  image: 
    repository: images.paas.redhat.com/unifai/multiagent
    tag: "latest"
  service:
    type: ClusterIP
    port: "8003"
  env:
    BACKEND_ENV: "production" #options - production development
    ROLE: "serve" # options are flask celery debug
    GUNICORN_WORKERS: "9"
    GUNICORN_THREADS: "8"
    GUNICORN_TIMEOUT: "600"
    SHARED_STORAGE: "/app/shared"
    GOOGLE_APPLICATION_CREDENTIALS: "/opt/app-root/src/config/gcp/gcp-sa-key.json"
    LANGFUSE_ENABLED: true
    LANGFUSE_BASE_URL: "https://us.cloud.langfuse.com"
    VERSION: ""

multiagent_temporal_worker:
  replicaCount: 1
  resources:
    limits:
      cpu: '1'
      memory: '2Gi'
    requests:
      cpu: '1'
      memory: '2Gi'
  image:
    repository: images.paas.redhat.com/unifai/multiagent
    tag: "latest"
  service:
    type: ClusterIP
    port: "8003"
  env:
    BACKEND_ENV: "production" #options - production development
    ROLE: "temporal-worker" # options are flask celery debug
    WORKER_THREADS: "100"
    SHARED_STORAGE: "/app/shared"
    GOOGLE_APPLICATION_CREDENTIALS: "/opt/app-root/src/config/gcp/gcp-sa-key.json"
    LANGFUSE_ENABLED: true
    LANGFUSE_BASE_URL: "https://us.cloud.langfuse.com"
    VERSION: ""

storage:
  volumeName: unifai-multiagent-shared-storage
  requestedSize: 50Gi
  className: aws-efs-tier-c1
  accessModes:
    - ReadWriteMany
  keepPvc: true
  annotations:
    kubernetes.io/reclaimPolicy: Delete
  labels:
    paas.redhat.com/appcode: TAG-001