multiagent_server:
  resources: 
    limits:
      cpu: '8'
      memory: '16Gi'
    requests:
      cpu: '4'
      memory: '8Gi'
  image: 
    repository: images.paas.redhat.com/unifai/multiagent
    tag: "latest"
  service:
    type: ClusterIP
    port: "8003"
  env:
    BACKEND_ENV: "production" #options - production development
    ROLE: "flask" # options are flask celery debug
    GUNICORN_WORKERS: "15"
    GUNICORN_THREADS: "16"
    GUNICORN_TIMEOUT: "600"
    VERSION: ""