env:
    qdrant_ip: "http://qdrant"
    qdrant_port: "6333"
    SHARED_STORAGE: "/app/shared"

unifai_rag_server:
  debug: false
  replicaCount: 1
  image:
    repository: images.paas.redhat.com/unifai/rag
    tag: "latest"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 13456
  env:
    ROLE: "flask"
    SHARED_STORAGE: "/app/shared"
    BACKEND_URL: "http://unifai-backend:8005"
    VERSION: ""
    DOCLING_SERVICE_URL: "https://docling-service-tag-ai--runtime-int.apps.stc-ai-e1-pp.imap.p1.openshiftapps.com"
    DOCLING_PDF_BACKEND: "dlparse_v4"
    EMBEDDING_SERVICE_URL: "https://embedding-service-tag-ai--runtime-int.apps.stc-ai-e1-pp.imap.p1.openshiftapps.com"
    USE_REMOTE_DOCLING: "True"
    USE_REMOTE_EMBEDDING: "True"
    OTEL_LOGS_ENABLED: "true"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://unifai-logging:4317"
    OTEL_EXPORTER_OTLP_INSECURE: "true"
    #FRONTEND_URL: "http://unifai-ui-tag-ai--pipeline.apps.stc-ai-e1-pp.imap.p1.openshiftapps.com"
  resources:
    limits:
      cpu: 4
      memory: 12Gi
    requests:
      cpu: 4
      memory: 12Gi


unifai_rag_celery:
  debug: false
  replicaCount: 1
  image:
    repository: images.paas.redhat.com/unifai/rag
    tag: "latest"
    pullPolicy: Always
  env:
    ROLE: "celery"
    SHARED_STORAGE: "/app/shared"
    BACKEND_URL: "http://unifai-backend:8005"
    CELERY_QUEUES: "slack_queue,document_queue,slack_events_queue"
    CELERY_WORKER: 8
    CELERY_POOL: "prefork"
    VERSION: ""
    DOCLING_SERVICE_URL: "https://docling-service-tag-ai--runtime-int.apps.stc-ai-e1-pp.imap.p1.openshiftapps.com"
    DOCLING_PDF_BACKEND: "dlparse_v4"
    EMBEDDING_SERVICE_URL: "https://embedding-service-tag-ai--runtime-int.apps.stc-ai-e1-pp.imap.p1.openshiftapps.com"
    USE_REMOTE_DOCLING: "True"
    USE_REMOTE_EMBEDDING: "True"
    OTEL_LOGS_ENABLED: "true"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://unifai-logging:4317"
    OTEL_EXPORTER_OTLP_INSECURE: "true"
  resources:
    limits:
      cpu: 4
      memory: 8Gi
    requests:
      cpu: 2
      memory: 4Gi
  tolerations: []


unifai_rag_celery_beat:
  debug: false
  replicaCount: 1
  image:
    repository: images.paas.redhat.com/unifai/rag
    tag: "latest"
    pullPolicy: Always
  env:
    ROLE: "celery-beat"
    SHARED_STORAGE: "/app/shared"
    VERSION: ""
    OTEL_LOGS_ENABLED: "true"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://unifai-logging:4317"
    OTEL_EXPORTER_OTLP_INSECURE: "true"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
storage:
  volumeName: unifai-rag-shared-storage
  requestedSize: 100Gi
  className: aws-efs-tier-c1
  accessModes:
    - ReadWriteMany
  annotations:
    kubernetes.io/reclaimPolicy: Delete
  labels:
    paas.redhat.com/appcode: TAG-001
