storage:
  volumeName: unifai-multiagent-shared-storage
  requestedSize: 50Gi
  className: aws-efs-tier-c1
  accessModes:
    - ReadWriteMany
  keepPvc: true
  annotations:
    kubernetes.io/reclaimPolicy: Delete
  labels:
    paas.redhat.com/appcode: TAG-001
