{{- if .Values.serviceDiscovery.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceDiscovery.rbac.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shared-config.labels" . | nindent 4 }}
  annotations:
    {{- if hasKey .Values.global "syncWave" }}
    argocd.argoproj.io/sync-wave: {{ .Values.global.syncWave | quote }}
    {{- else }}
    argocd.argoproj.io/sync-wave: "3"
    {{- end }}
{{- end }}
