#!/usr/bin/env python3
"""
UnifAI Workflow Execution Script
================================

This script executes a workflow session on the UnifAI platform via API calls.
It creates a session from a blueprint, submits a user prompt, polls for completion,
and returns the final answer generated by the workflow.

Usage:
------
    # Using blueprint ID (direct)
    python execution_workflow.py --blueprint-id <ID> --user <SHORTCUT> --question "Your prompt here"

    # Using blueprint name (resolved to ID via API)
    python execution_workflow.py --blueprint-name "My Workflow" --user ocohen --question "Hello"

    # With custom polling interval and base URL
    python execution_workflow.py \
        --blueprint-id abc-123 \
        --user ocohen \
        --question "Summarize the latest project updates" \
        --polling-interval 10 \
        --base-url https://custom-unifai.example.com

Environment Variables (alternative to CLI args):
------------------------------------------------
    BLUEPRINT_ID        - Blueprint ID to execute (takes priority over name)
    BLUEPRINT_NAME      - Blueprint name to resolve (used if ID not provided)
    USER_SHORTCUT       - User shortcut (e.g., ocohen for Ohad Cohen)
    POLLING_INTERVAL    - Status polling interval in seconds (5-60, default: 10)
    USER_QUESTION       - Prompt to send to the workflow
    UNIFAI_BASE_URL     - Base URL (default: https://unifai-ui-tag-ai--pipeline.apps.stc-ai-e1-prod.rtc9.p1.openshiftapps.com)

Blueprint Resolution:
---------------------
- If --blueprint-id is provided, it is used directly.
- If only --blueprint-name is provided, the script queries available blueprints for the user
  and resolves the name to an ID. The name must be unique; if multiple blueprints share
  the same name, the script exits with an error.
- At least one of --blueprint-id or --blueprint-name must be provided.

Flow:
-----
1. Resolve blueprint (by ID or name lookup)
2. Create session from blueprint (POST /user.session.create)
3. Submit session with user prompt (POST /user.session.submit)
4. Poll session status until completion (GET /session.stream.status)
5. Retrieve and return final answer (GET /session.chat.get)
"""

import argparse
import os
import sys
import time
import urllib3
from dataclasses import dataclass
from typing import Optional

import requests

# Suppress SSL warnings for internal routes
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


# =============================================================================
# Configuration
# =============================================================================

DEFAULT_BASE_URL = "https://unifai-ui-tag-ai--pipeline.apps.stc-ai-e1-prod.rtc9.p1.openshiftapps.com"
DEFAULT_POLLING_INTERVAL = 10
MIN_POLLING_INTERVAL = 5
MAX_POLLING_INTERVAL = 60
SESSION_API_PREFIX = "/api2/sessions"
BLUEPRINTS_API_PREFIX = "/api2/blueprints"


@dataclass
class WorkflowConfig:
    """Configuration for workflow execution."""
    user_shortcut: str
    user_question: str
    polling_interval: int
    base_url: str
    blueprint_id: Optional[str] = None
    blueprint_name: Optional[str] = None

    def __post_init__(self):
        if not MIN_POLLING_INTERVAL <= self.polling_interval <= MAX_POLLING_INTERVAL:
            raise ValueError(
                f"polling_interval must be between {MIN_POLLING_INTERVAL} and {MAX_POLLING_INTERVAL} seconds, "
                f"got {self.polling_interval}"
            )
        self.base_url = self.base_url.rstrip("/")
        
        if not self.blueprint_id and not self.blueprint_name:
            raise ValueError("Either blueprint_id or blueprint_name must be provided")

    @property
    def api_base(self) -> str:
        return f"{self.base_url}{SESSION_API_PREFIX}"
    
    @property
    def blueprints_api_base(self) -> str:
        """Base URL for blueprints API (different prefix)."""
        return f"{self.base_url}{BLUEPRINTS_API_PREFIX}"


# =============================================================================
# API Client
# =============================================================================

class UnifAIClient:
    """HTTP client for UnifAI session APIs."""

    def __init__(self, config: WorkflowConfig):
        self.config = config
        self.session = requests.Session()
        self.session.headers.update({
            "Content-Type": "application/json",
            "X-Authenticated-User": config.user_shortcut,
        })
        self.session.verify = False  # Disable SSL verification for internal routes

    def _url(self, endpoint: str) -> str:
        return f"{self.config.api_base}/{endpoint}"

    def _handle_response(self, response: requests.Response, context: str) -> dict:
        """Handle API response, raising descriptive errors on failure."""
        if not response.ok:
            error_detail = response.text[:500] if response.text else "No details"
            raise RuntimeError(
                f"{context} failed with status {response.status_code}: {error_detail}"
            )
        return response.json()


# =============================================================================
# Workflow Steps (each step is a separate method)
# =============================================================================

def resolve_blueprint_id(client: UnifAIClient) -> str:
    """
    Resolve the blueprint ID from either direct ID or name lookup.
    
    Priority:
    1. If blueprint_id is provided, use it directly
    2. If only blueprint_name is provided, look it up via API
    
    Returns:
        blueprint_id: The resolved blueprint ID.
        
    Raises:
        RuntimeError: If blueprint name is not found or not unique.
    """
    config = client.config
    
    # If ID is provided, use it directly
    if config.blueprint_id:
        print(f"[0/5] Using provided blueprint ID: {config.blueprint_id}")
        return config.blueprint_id
    
    # Otherwise, resolve name to ID
    print(f"[0/5] Resolving blueprint name '{config.blueprint_name}'...")
    
    url = f"{config.blueprints_api_base}/available.blueprints.summary.get"
    params = {"userId": config.user_shortcut}
    
    response = client.session.get(url, params=params)
    summaries = client._handle_response(response, "Blueprint lookup")
    
    # API returns a list of BlueprintSummary objects with fields:
    # blueprint_id, user_id, name, description, created_at, updated_at, metadata
    
    # Find blueprints matching the name (case-insensitive)
    target_name = config.blueprint_name.lower().strip()
    matches = [
        bp for bp in summaries
        if bp.get("name", "").lower().strip() == target_name
    ]
    
    if not matches:
        available_names = sorted(set(bp.get("name", "Untitled") for bp in summaries))
        raise RuntimeError(
            f"Blueprint '{config.blueprint_name}' not found for user '{config.user_shortcut}'.\n"
            f"Available blueprints: {', '.join(available_names[:10])}"
            + (f" ... and {len(available_names) - 10} more" if len(available_names) > 10 else "")
        )
    
    if len(matches) > 1:
        match_ids = [bp["blueprint_id"] for bp in matches]
        raise RuntimeError(
            f"Blueprint name '{config.blueprint_name}' is not unique - found {len(matches)} blueprints with this name.\n"
            f"Matching IDs: {', '.join(match_ids)}\n"
            f"Please use --blueprint-id to specify the exact blueprint, or rename duplicates to have unique names."
        )
    
    # Exactly one match found
    blueprint_id = matches[0]["blueprint_id"]
    print(f"      Resolved to ID: {blueprint_id}")
    return blueprint_id


def create_session(client: UnifAIClient, blueprint_id: str) -> str:
    """
    Step 1: Create a new session from the blueprint.
    
    Args:
        client: The UnifAI API client.
        blueprint_id: The resolved blueprint ID.
    
    Returns:
        session_id: The unique identifier for the created session.
    """
    url = client._url("user.session.create")
    payload = {
        "blueprintId": blueprint_id,
        "userId": client.config.user_shortcut,
    }

    print(f"[1/5] Creating session for blueprint '{blueprint_id}'...")
    response = client.session.post(url, json=payload)
    session_id = client._handle_response(response, "Session creation")

    if isinstance(session_id, dict):
        session_id = session_id.get("sessionId") or session_id.get("session_id")
    
    print(f"      Session created: {session_id}")
    return session_id


def submit_session(client: UnifAIClient, session_id: str) -> dict:
    """
    Step 2: Submit the session for background execution with the user prompt.
    
    Returns:
        Response containing sessionId and workflowId.
    """
    url = client._url("user.session.submit")
    payload = {
        "sessionId": session_id,
        "inputs": {"user_prompt": client.config.user_question},
        # "scope": "public",
        "userId": client.config.user_shortcut,
    }

    print(f"[2/5] Submitting session with prompt: '{client.config.user_question[:50]}...'")
    response = client.session.post(url, json=payload)
    result = client._handle_response(response, "Session submission")
    
    workflow_id = result.get("workflowId", "N/A")
    print(f"      Session submitted (workflow: {workflow_id})")
    return result


def poll_session_status(client: UnifAIClient, session_id: str) -> None:
    """
    Step 3: Poll session status until execution completes.
    
    Polls the session.stream.status endpoint at the configured interval
    until is_active becomes False (or stream is removed after completion).
    """
    url = client._url("session.stream.status")
    params = {"sessionId": session_id}
    interval = client.config.polling_interval

    print(f"[3/5] Polling session status every {interval}s...")

    poll_count = 0
    seen_active = False  # Track if we've seen the session running
    
    while True:
        poll_count += 1
        response = client.session.get(url, params=params)
        
        try:
            status = client._handle_response(response, "Status poll")
        except RuntimeError as e:
            if "404" in str(e):
                if poll_count == 1:
                    # Session not yet initialized, wait and retry
                    print(f"      Waiting for session to initialize...")
                    time.sleep(interval)
                    continue
                elif seen_active:
                    # We saw the session running before, 404 means stream was cleaned up after completion
                    print(f"      Session stream removed (session completed)")
                    return
            raise

        is_active = status.get("is_active", False)
        event_count = status.get("event_count", 0)
        
        if is_active:
            seen_active = True
        
        print(f"      Poll #{poll_count}: events={event_count}, active={is_active}")
        
        if not is_active:
            print(f"      Session completed after {poll_count} polls")
            return

        time.sleep(interval)


def get_final_answer(client: UnifAIClient, session_id: str) -> str:
    """
    Step 4: Retrieve the final answer from the completed session.
    
    Uses the lightweight session.chat.get endpoint that returns only
    messages and output fields.
    
    Returns:
        The final output/answer generated by the workflow.
    """
    url = client._url("session.chat.get")
    params = {"sessionId": session_id}

    print(f"[4/5] Retrieving final answer...")
    response = client.session.get(url, params=params)
    result = client._handle_response(response, "Get final answer")
    
    output = result.get("output", "")
    if not output:
        output = result.get("response", result.get("answer", ""))
    
    if not output:
        print("      Warning: No output found in session state")
        return ""
    
    print(f"      Answer retrieved ({len(output)} chars)")
    return output


# =============================================================================
# Main Orchestrator
# =============================================================================

def execute_workflow(config: WorkflowConfig) -> str:
    """
    Execute the complete workflow and return the final answer.
    
    This orchestrator method calls each workflow step in sequence:
    0. Resolve blueprint ID (from ID or name)
    1. Create session
    2. Submit session
    3. Poll until complete
    4. Get final answer
    
    Returns:
        The final answer generated by the workflow.
    """
    client = UnifAIClient(config)

    print("=" * 60)
    print("UnifAI Workflow Execution")
    print("=" * 60)
    if config.blueprint_id:
        print(f"Blueprint ID:   {config.blueprint_id}")
    if config.blueprint_name:
        print(f"Blueprint Name: {config.blueprint_name}")
    print(f"User:           {config.user_shortcut}")
    print(f"Base URL:       {config.base_url}")
    print(f"Polling:        {config.polling_interval}s")
    print("=" * 60)

    blueprint_id = resolve_blueprint_id(client)
    session_id = create_session(client, blueprint_id)
    submit_session(client, session_id)
    poll_session_status(client, session_id)
    final_answer = get_final_answer(client, session_id)

    return final_answer


# =============================================================================
# CLI Interface
# =============================================================================

def parse_args() -> WorkflowConfig:
    """Parse command-line arguments and environment variables."""
    parser = argparse.ArgumentParser(
        description="Execute a UnifAI workflow session and return the final answer.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Using blueprint ID
  python execution_workflow.py --blueprint-id abc-123 --user ocohen --question "Hello world"
  python execution_workflow.py -b abc-123 -u ocohen -q "Hello" --polling-interval 5
  
  # Using blueprint name (resolved to ID via API)
  python execution_workflow.py --blueprint-name "My Workflow" --user ocohen --question "Hello"
  python execution_workflow.py -n "My Workflow" -u ocohen -q "Hello"
        """,
    )

    parser.add_argument(
        "-b", "--blueprint-id",
        default=os.getenv("BLUEPRINT_ID"),
        help="Blueprint ID to execute (env: BLUEPRINT_ID). Takes priority over --blueprint-name.",
    )
    parser.add_argument(
        "-n", "--blueprint-name",
        default=os.getenv("BLUEPRINT_NAME"),
        help="Blueprint name to resolve (env: BLUEPRINT_NAME). Used if --blueprint-id not provided. Must be unique for the user.",
    )
    parser.add_argument(
        "-u", "--user",
        default=os.getenv("USER_SHORTCUT"),
        help="User shortcut, e.g., 'ocohen' (env: USER_SHORTCUT)",
    )
    parser.add_argument(
        "-q", "--question",
        default=os.getenv("USER_QUESTION"),
        help="Prompt/question for the workflow (env: USER_QUESTION)",
    )
    parser.add_argument(
        "-p", "--polling-interval",
        type=int,
        default=int(os.getenv("POLLING_INTERVAL", DEFAULT_POLLING_INTERVAL)),
        help=f"Status polling interval in seconds ({MIN_POLLING_INTERVAL}-{MAX_POLLING_INTERVAL}, default: {DEFAULT_POLLING_INTERVAL})",
    )
    parser.add_argument(
        "--base-url",
        default=os.getenv("UNIFAI_BASE_URL", DEFAULT_BASE_URL),
        help="UnifAI base URL (env: UNIFAI_BASE_URL)",
    )

    args = parser.parse_args()

    if not args.blueprint_id and not args.blueprint_name:
        parser.error("Either --blueprint-id or --blueprint-name is required (or set BLUEPRINT_ID/BLUEPRINT_NAME env var)")
    if not args.user:
        parser.error("--user is required (or set USER_SHORTCUT env var)")
    if not args.question:
        parser.error("--question is required (or set USER_QUESTION env var)")

    return WorkflowConfig(
        user_shortcut=args.user,
        user_question=args.question,
        polling_interval=args.polling_interval,
        base_url=args.base_url,
        blueprint_id=args.blueprint_id,
        blueprint_name=args.blueprint_name,
    )


def main() -> int:
    """Main entry point."""
    try:
        config = parse_args()
        final_answer = execute_workflow(config)
        
        print("\n" + "=" * 60)
        print("FINAL ANSWER")
        print("=" * 60)
        print(final_answer)
        print("=" * 60)
        
        return 0

    except ValueError as e:
        print(f"Configuration error: {e}", file=sys.stderr)
        return 1
    except requests.RequestException as e:
        print(f"Network error: {e}", file=sys.stderr)
        return 2
    except RuntimeError as e:
        print(f"API error: {e}", file=sys.stderr)
        return 3
    except KeyboardInterrupt:
        print("\nExecution cancelled by user", file=sys.stderr)
        return 130


if __name__ == "__main__":
    sys.exit(main())
