apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sso.fullname" . }}
  labels:
    {{- include "sso.labels" . | nindent 4 }}
  annotations:
    {{- if hasKey .Values.global "syncWave" }}
    argocd.argoproj.io/sync-wave: {{ .Values.global.syncWave | quote }}
    {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sso.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sso.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sso.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        # ========================
        # Backend Container
        # ========================
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: {{ .Values.backend.service.name }}
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP

          env:
          {{- range $key, $value := .Values.backend.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
          {{- end }}
          {{- range $key, $value := .Values.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
          {{- end }}

