#podman run -dt   --name helmfile   --user $(id -u):$(id -g)   --workdir /helm/charts   -v "$PWD":/helm/charts:Z   -v "$HOME/.kube":/helm/.kube:Z   ghcr.io/helmfile/helmfile:latest bash
environments:
  default:
    values:
      - ./values/shared-resource-values.yaml
---

helmDefaults:
  createNamespace: false
  wait: false

releases:
  - name: unifai-mongodb
    chart: ./shared-resources/mongodb
    wait: true
    timeout: 300
    values:
      - {{- toYaml .Values.mongodb | nindent 8 }}

  - name: unifai-qdrant
    chart: ./shared-resources/qdrant
    wait: true
    timeout: 300
    values:
      - {{- toYaml .Values.qdrant | nindent 8 }}

  - name: unifai-rabbitmq
    chart: ./shared-resources/rabbitmq
    wait: true
    values:
      - ./values/shared-resource-values.yaml
      #- valuesKey: rabbitmq

  - name: unifai-docling-service
    chart: ./shared-resources/docling-service
    wait: true
    timeout: 300
    values:
      - {{- toYaml .Values.docling | nindent 8 }}
  - name: unifai-shared-config
    chart: ./shared-resources/shared-config
    wait: true
    needs:
      - unifai-mongodb
      - unifai-qdrant
      - unifai-rabbitmq
      - unifai-docling-service
    hooks:
      - events: ["postsync"]
        showlogs: true
        command: bash
        args:
          - "-c"
          - |
              set -x  # Print each command
              set +e  # Disable immediate exit on error
              echo "Starting postsync hook..."

              wait_for_port() {
                local svc=$1
                local ip=""
                for i in {1..60}; do
                  port=$(kubectl get svc "$svc" -o jsonpath='{.spec.ports[0].port}' 2>/dev/null)
                  if [[ -n "$port" ]]; then
                    echo "$port"
                    return
                  fi
                  echo "Waiting for $svc Port..."
                  sleep 10
                done
                echo "pending"
              }

              wait_for_service_name() {
                local svc=$1
                local ip=""
                for i in {1..60}; do
                  ip=$(kubectl get svc "$svc" -o jsonpath='{.metadata.name}' 2>/dev/null)
                  if [[ -n "$ip" ]]; then
                    echo "$ip"
                    return
                  fi
                  echo "Waiting for $svc LoadBalancer IP..."
                  sleep 10
                done
                echo "pending"
              }

              wait_for_ext_ip() {
                local svc=$1
                local ip=""
                for i in {1..60}; do
                  ip=$(kubectl get svc "$svc" -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null)
                  if [[ -n "$ip" ]]; then
                    echo "$ip"
                    return
                  fi
                  echo "Waiting for $svc LoadBalancer IP..."
                  sleep 10
                done
                echo "pending"
              }

              MONGODB_ADDR=$(wait_for_ext_ip mongodb)
              QDRANT_ADDR=$(wait_for_ext_ip qdrant)
              RABBITMQ_ADDR=$(wait_for_ext_ip rabbitmq)
              DOCLING_ADDR=$(wait_for_ext_ip docling-service)

              MONGO_PORT=$(wait_for_port mongodb)
              RMQ_PORT=$(wait_for_port rabbitmq)
              DOCLING_PORT=$(wait_for_port docling-service)

              MONGO_IP=$(wait_for_service_name mongodb)
              RMQ_IP=$(wait_for_service_name rabbitmq)
              DOCLING_IP=$(wait_for_service_name docling-service)
              

              kubectl delete configmap shared-config
              kubectl create configmap shared-config \
                --from-literal=MONGO_EXT_ADDR="$MONGODB_ADDR" \
                --from-literal=RABBITMQ_EXT_ADDR="$RABBITMQ_ADDR" \
                --from-literal=QDRANT_EXT_ADDR="$QDRANT_ADDR" \
                --from-literal=DOCLING_EXT_ADDR="$DOCLING_ADDR" \
                --from-literal=MONGODB_PORT="$MONGO_PORT" \
                --from-literal=RABBITMQ_PORT="$RMQ_PORT" \
                --from-literal=DOCLING_PORT="$DOCLING_PORT" \
                --from-literal=MONGODB_IP="$MONGO_IP" \
                --from-literal=RABBITMQ_IP="$RMQ_IP" \
                --from-literal=DOCLING_IP="$DOCLING_IP" \
                --dry-run=client -o yaml | kubectl apply -f -
